#!/bin/sh
# Problem library questions go to the my home directory;
# there are symlinks from there to the courses
export COLL="math132b"
export SRC_DIR=$COLL
export TARGET_DIR="problems/$COLL"
export SERVER="webworknotty"
export USER="library"
rsync -arv --delete --progress -e ssh $SRC_DIR/ ${USER}@$SERVER:$TARGET_DIR/
